# Generated by Django 2.2 on 2019-04-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Movie Description')),
                ('year', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
